### ISSUE TITLE
Tox IDs aren't fully shown

### ISSUE THREAD

**Issue by LoneWolfHT** [evilcorpltd/aTox#1014]
I downloaded aTox via F-droid onto a Galaxy S20 FE and it looks like you can't see the full tox ID on profiles, it's always missing 12 characters

**Comment by robinlinden** [comment]
That's part of the design of Tox. The Tox ID consists of a public key, a nospam value, and a checksum. Users can change their nospam, leading to the last 12 characters changing, so there's no way for clients to display a Tox ID that's guaranteed to work. I know one client event randomizes the nospam after every contact added, so the Tox ID you got from your contact will **never** be correct after you send a friend request if it came from that client.

See: https://toktok.ltd/spec#messenger

I am working on a onboarding page that will explain some of these things since it can be a bit confusing. :x

**Comment by LoneWolfHT** [comment]
Ok, I think I mostly understand now.

How would I send a friend's ID to another friend so they could add them?

**Comment by robinlinden** [comment]
You'd have to ask your friend for their ID. There's no other way of getting an ID that's guaranteed to work. :(

**Comment by LoneWolfHT** [comment]
Alrighty, thanks for the explanation! This'll only be a minor inconvenience
