### ISSUE TITLE
Add application to f-droid

### ISSUE THREAD

**Issue by wuniversales** [evilcorpltd/aTox#376]

**Comment by robinlinden** [comment]
Definitely planned as soon as I've got all the basic functionality implemented. Right now I'm thinking I want file transfers and avatars in before that. Group chats would be nice, but I don't think it's mandatory before then. :)

**Comment by wuniversales** [comment]
Perfect :)

**Comment by readyblue** [comment]
You may be interested in publishing your app as beta version to IzzyOnDroid (private f-droid repo) [https://android.izzysoft.de/repo](url). It is useful because you do not need to met all the strict rules that main F-droid repo have. It also may draw some more attention, because IzzyOnDroid is quite a popular. Check with Izzy @IzzySoft the owner of the repo for details.

**Comment by readyblue** [comment]
If you add IzzyOnDroid repo, you can test the app already
[https://android.izzysoft.de/repo/apk/ltd.evilcorp.atox](url)

**Comment by robinlinden** [comment]
Merge request adding aTox to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6571 (still in-progress)

**Comment by robinlinden** [comment]
#541 added scripts and a CI target for building aTox w/ deps from source.

**Comment by robinlinden** [comment]
Issue in F-Droid re: aTox: https://gitlab.com/fdroid/rfp/-/issues/1631
