### ISSUE TITLE
🐛 Problems with calls on new calls feature

### ISSUE THREAD

**Issue by Tha14** [evilcorpltd/aTox#749]
When making a call, my mobile is transmitting audio which on the other end sounds as if it's being cut off every few miliseconds. When receiving audio on my mobile from the other end the sound is high pitched and equality dropping out.

aTox version last tested: 0.7.0-pre6
Device: Redmi 4x
Android 10(was happening on Android 9 aswell)
Rom: Resurrection Remix 8.6.5

**Comment by robinlinden** [comment]
Since we talked about this on IRC, I probably don't need to comment here, but for transparency for everyone not on there..

No other testers have reported it, but the outgoing audio frame timing doesn't match the audio sender event loop time, so I'll look into it! Good report and I'll try to get it sorted before 0.7.0 is properly released. :)

**Comment by Joe-abdo** [comment]
Can't wait for the next update :) <br />

**Comment by robinlinden** [comment]
@Joe-abdo Happy to hear it! Always looking for more testers if you want to check the new features early too. 😁 (Just join IRC and the latest nightly is linked in the topic.)
It's nearing completion, with some bug fixes and polish in audio calls needed and encryption needing to be finished.

**Comment by robinlinden** [comment]
Resolved by #882.
