### ISSUE TITLE
Contact's Tox ID is incomplete

### ISSUE THREAD

**Issue by theAkito** [evilcorpltd/aTox#869]
I tried to add the Tox ID of a contact in a different Tox client. I got an "incorrect ToxID" error. So I checked the Tox ID of the contact inside this app and indeed - it's missing the last ~15 characters of the ID.

It'd be nice to be able to not only see the full ID, but also to copy it with one click, instead of being forced to manually select the ID and then copy it manually.

**Comment by robinlinden** [comment]
That's part of the design of Tox. The Tox ID consists of a public key, a nospam value, and a checksum. Users can change their nospam, leading to the last 12 characters changing, so there's no way for clients to display a Tox ID that's guaranteed to work. I know one client event randomizes the nospam after every contact added, so the Tox ID you got from your contact will **never** be correct after you send a friend request if it came from that client.

See: https://toktok.ltd/spec#messenger

I am working on a onboarding page that will explain some of these things since it can be a bit confusing. :x

**Comment by theAkito** [comment]
Okay. Never dove that deep into Tox. Just have been using on and off since it came out. I wanted to easily copy the ID from one app to the other, but apparently I need to do it the inconvenient way.
