### ISSUE TITLE
Add ability to change own photo/picture/icon

### ISSUE THREAD

**Issue by zellchristensen** [evilcorpltd/aTox#975]
Maybe I'm missing something but, there doesn't seem to be a way to change the profile photo from the menus.
Short and long presses on my name/icon area don't do anything.
I saw screenshots on https://github.com/evilcorpltd/aTox/pull/46 with the android head icons and thought maybe those would allow it since they seem to reference changing it but the two older builds I tried (0.6.0 and 0.5.1 on FDroid) didn't seem to work either. 
On the newest build (0.7.2), I just don't have any icon at all.
Maybe I disabled something on my phone that it relies on?

![image](https://user-images.githubusercontent.com/38737447/152678419-dc3a5a7a-17be-49a2-a3fd-090b0ca6107a.png)
![image](https://user-images.githubusercontent.com/38737447/152678369-2d32ba26-8865-4414-86e6-15cd0724802b.png)

**Comment by robinlinden** [comment]
Hi! You can't find it because it hasn't been implemented yet. I think it'll be part of the next release though as @roihershberg started doing some work to support it, but no promises yet.

The older releases had those Android heads in place of an avatar because I was prototyping the GUI. :P They've been dropped since then since it was confusing to have a random avatar placeholder there.

Development of this is tracked in #717, so this is a duplicate issue.
